version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - pocketbase
    networks:
      - banco-network

  pocketbase:
    image: pocketbase/pocketbase:latest
    container_name: pocketbase
    volumes:
      - ./pb_data:/pb_data
    ports:
      - "8090:8090"
    command: serve --http=0.0.0.0:8090
    networks:
      - banco-network

networks:
  banco-network:
    driver: bridge
